version: "3.10"
services:
  database:
    image: postgres:15.1-alpine
    container_name: database
    env_file:
      - .env_prod
    healthcheck:
      test: /bin/bash -c "pg_isready -d database -U someuser"
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - .env_prod
    depends_on:
      - database
    healthcheck:
      test: /bin/bash -c "redis-cli ping"
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
    container_name: api
    env_file:
      - .env_prod
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: /bin/bash -c "python create_key.py && alembic upgrade head && python -m uvicorn main:app --host 0.0.0.0 --port 8000"
